name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  EXTNAME: WikiMirror
  MW_INSTALL_PATH: ${{ github.workspace }}

jobs:
  style:
    name: Code Style
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.4' ]
        mediawiki: [ REL1_35, master ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          coverage: none
          tools: composer, phpcs, phplint
      - name: Setup MediaWiki
        uses: actions/checkout@v2
        with:
          repository: wikimedia/mediawiki
          ref: ${{ matrix.mediawiki }}
      - name: Setup VisualEditor
        uses: actions/checkout@v2
        with:
          repository: wikimedia/mediawiki-extensions-VisualEditor
          ref: ${{ matrix.mediawiki }}
          path: extensions/VisualEditor
          submodules: true
      - name: Setup Extension
        uses: actions/checkout@v2
        with:
          path: extensions/${{ env.EXTNAME }}
      - name: Setup Composer
        run: |
          echo '{"extra":{"merge-plugin":{"include":["extensions/*/composer.json","skins/*/composer.json"]}}}' > composer.local.json
          composer update
          composer update
      - name: Lint
        run: phplint -w extensions/${{ env.EXTNAME }}
      - name: PHP Code Sniffer
        run: phpcs -sp --standard=vendor/mediawiki/mediawiki-codesniffer/MediaWiki extensions/${{ env.EXTNAME }}

  security:
    name: Static Analysis
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.4' ]
        mediawiki: [ master ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, ast
          ini-values: auto_prepend_file=${{ env.MW_INSTALL_PATH }}/vendor/autoload.php
          coverage: none
          tools: composer, phan
      - name: Setup MediaWiki
        uses: actions/checkout@v2
        with:
          repository: wikimedia/mediawiki
          ref: ${{ matrix.mediawiki }}
      - name: Setup VisualEditor
        uses: actions/checkout@v2
        with:
          repository: wikimedia/mediawiki-extensions-VisualEditor
          ref: ${{ matrix.mediawiki }}
          path: extensions/VisualEditor
          submodules: true
      - name: Setup Extension
        uses: actions/checkout@v2
        with:
          path: extensions/${{ env.EXTNAME }}
      - name: Setup Composer
        run: |
          echo '{"extra":{"merge-plugin":{"include":["extensions/*/composer.json","skins/*/composer.json"]}}}' > composer.local.json
          composer update
          composer update
      - name: Phan
        run: phan -d extensions/${{ env.EXTNAME }} --minimum-target-php-version=7.3 --long-progress-bar
